// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_XfePcQDFA6ta5HQTLVVU6F6lr1zdyUY',
    appId: '1:812142427219:web:108c94a64ae43208831aa6',
    messagingSenderId: '812142427219',
    projectId: 'chat-app-ec787',
    authDomain: 'chat-app-ec787.firebaseapp.com',
    storageBucket: 'chat-app-ec787.appspot.com',
    measurementId: 'G-R5SG2S2LH3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwF9-Jyk1dg0iYadLjrJ0CZiOwtFD8yPs',
    appId: '1:812142427219:android:1b2993e51d46ed46831aa6',
    messagingSenderId: '812142427219',
    projectId: 'chat-app-ec787',
    storageBucket: 'chat-app-ec787.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtywNJQWUftgvq20FSe4pgDdLQdR0Wwuk',
    appId: '1:812142427219:ios:2c7a9791907091e4831aa6',
    messagingSenderId: '812142427219',
    projectId: 'chat-app-ec787',
    storageBucket: 'chat-app-ec787.appspot.com',
    androidClientId: '812142427219-7s23ac8mke8kvumpqbj9c5bj3bc7apfu.apps.googleusercontent.com',
    iosClientId: '812142427219-id3jet66onc88kocgop8d5f8pajo6llq.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtywNJQWUftgvq20FSe4pgDdLQdR0Wwuk',
    appId: '1:812142427219:ios:6d4034a6b521eb34831aa6',
    messagingSenderId: '812142427219',
    projectId: 'chat-app-ec787',
    storageBucket: 'chat-app-ec787.appspot.com',
    androidClientId: '812142427219-7s23ac8mke8kvumpqbj9c5bj3bc7apfu.apps.googleusercontent.com',
    iosClientId: '812142427219-hma3oj8pd944rl8a09qh91qvcj2a0dln.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
